Added missing translation files
sumocoders/wireframes pull request #4
Opened 2018-05-24 15:38 UTC by tijsverkoyen

2018-05-25 09:26 UTC, ohvitorino requested changes

2018-05-25 09:26 UTC, ohvitorino commented on translations/messages.nl.yaml
> +        oldBrowser: <strong>Warning:</strong> You are using an older browser. If you want to see the site as it is intended, you may want to download a new version or a decent browser like <a href="h
Still needs to be translated.

2018-05-25 09:26 UTC, ohvitorino commented on translations/messages.nl.yaml
> +  pickDate: pick a date
idem

2018-05-25 09:26 UTC, ohvitorino commented on translations/messages.nl.yaml
> +  buttons:
idem

2018-05-30 09:16 UTC, tijsverkoyen commented
@ohvitorino fixed in https://github.com/sumocoders/wireframes/pull/4/commits/ea3070f964ad08b3a9839d4c324f05217df50f56

2018-05-30 09:19 UTC, ohvitorino approved these changes

2018-05-30 09:19 UTC, ohvitorino commented
👍

2018-05-30 09:19 UTC, merged